/**
 * UwoConnect Product Tour Configuration
 * ----------------------------------------
 * Each step has been shortened to keep cards clean and readable.
 */

const tourSteps = [
  {
    id: 'welcome',
    page: '/client',
    selector: '[data-tour="dashboard-welcome"]',
    title: '👋 Welcome to UwoConnect!',
    description: 'This is your automation command center. We will quickly show you around in 1 minute.',
    why: 'Helps you set up and run automations much faster.',
    tip: 'Press ESC to exit, or use the buttons below to navigate.',
    placement: 'bottom',
    icon: '🚀',
  },
  {
    id: 'sidebar-nav',
    page: null,
    selector: '[data-tour="sidebar-nav"]',
    title: '🗂️ Navigation Menu',
    description: 'Use the sidebar to navigate between all primary features.',
    why: 'Easily jump between Workflows, CRM, Inbox, and Settings.',
    tip: 'The active section has a green bar on the left.',
    placement: 'right',
    icon: '🗂️',
  },
  {
    id: 'dashboard-stats',
    page: '/client',
    selector: '[data-tour="dashboard-stats"]',
    title: '📊 Real-Time Stats',
    description: 'Monitor your automation runs, total conversations, and response speed here.',
    why: 'Gives an instant health check of your live integrations.',
    tip: null,
    placement: 'bottom',
    icon: '📊',
  },
  {
    id: 'dashboard-launch-btn',
    page: '/client',
    selector: '[data-tour="dashboard-launch-btn"]',
    title: '⚡ Build Flows',
    description: 'Click this button to immediately open the drag-and-drop workflow editor.',
    why: 'Instantly build customer sequences without deep navigation.',
    tip: null,
    placement: 'bottom',
    icon: '⚡',
  },
  {
    id: 'sidebar-channels',
    page: null,
    selector: '[data-tour="sidebar-channels"]',
    title: '🔗 Channels Setup',
    description: 'Connect your Instagram, Facebook, and WhatsApp API accounts here.',
    why: 'Required to receive and reply to customer chats.',
    tip: 'WhatsApp is highly recommended for marketing.',
    placement: 'right',
    icon: '🔗',
  },
  {
    id: 'sidebar-automations',
    page: null,
    selector: '[data-tour="sidebar-automations"]',
    title: '⚡ Auto Replies',
    description: 'Set simple keyword-based automatic replies for common questions.',
    why: 'Answers queries like pricing and timings 24/7.',
    tip: null,
    placement: 'right',
    icon: '⚡',
  },
  {
    id: 'sidebar-workflows',
    page: null,
    selector: '[data-tour="sidebar-workflows"]',
    title: '🔀 Visual Workflows',
    description: 'Create multi-step smart flows using visual builder cards.',
    why: 'Handles complex lead generation, appointments and logic.',
    tip: null,
    placement: 'right',
    icon: '🔀',
  },
  {
    id: 'sidebar-crm',
    page: null,
    selector: '[data-tour="sidebar-crm"]',
    title: '👥 Leads & CRM',
    description: 'Manage all customers who interacted with your automation.',
    why: 'Central database for user history and profile tags.',
    tip: null,
    placement: 'right',
    icon: '👥',
  },
  {
    id: 'sidebar-inbox',
    page: null,
    selector: '[data-tour="sidebar-inbox"]',
    title: '💬 Unified Inbox',
    description: 'A single workspace dashboard for manual team agent chats.',
    why: 'Allows you to easily take over chats from AI anytime.',
    tip: null,
    placement: 'right',
    icon: '💬',
  },
  {
    id: 'sidebar-campaigns',
    page: null,
    selector: '[data-tour="sidebar-campaigns"]',
    title: '📢 Broadcasts',
    description: 'Send bulk template messages or promotions to contacts.',
    why: 'Great for updates, announcement campaigns, and sales.',
    tip: null,
    placement: 'right',
    icon: '📢',
  },
  {
    id: 'sidebar-knowledge',
    page: null,
    selector: '[data-tour="sidebar-knowledge"]',
    title: '🧠 AI Knowledge Base',
    description: 'Upload documents or FAQs to train your AI chat assistant.',
    why: 'Ensures the AI answers with correct business context.',
    tip: null,
    placement: 'right',
    icon: '🧠',
  },
  {
    id: 'sidebar-team',
    page: null,
    selector: '[data-tour="sidebar-team"]',
    title: '👥 Team Members',
    description: 'Invite agents and configure custom access permissions.',
    why: 'Scale support and share chat responsibilities.',
    tip: null,
    placement: 'right',
    icon: '👥',
  },
  {
    id: 'sidebar-settings',
    page: null,
    selector: '[data-tour="sidebar-settings"]',
    title: '⚙️ Settings',
    description: 'Configure your company profile, API tokens, and options.',
    why: 'Core system config happens here.',
    tip: null,
    placement: 'right',
    icon: '⚙️',
  },
  {
    id: 'header-team-chat',
    page: null,
    selector: '[data-tour="header-team-chat"]',
    title: '💬 Live Team Room',
    description: 'Open the sidebar chat space to coordinate with online workspace agents.',
    why: 'Allows internal communication with team members in real-time.',
    tip: null,
    placement: 'bottom',
    icon: '💬',
  },
  {
    id: 'platform-assistant',
    page: null,
    selector: '[data-tour="platform-assistant"]',
    title: '✨ Platform Copilot',
    description: 'Ask our trained AI assistant helper how to use any platform tool.',
    why: 'Provides instant help without reading long manuals.',
    tip: null,
    placement: 'top',
    icon: '✨',
  },
  {
    id: 'sidebar-logout',
    page: null,
    selector: '[data-tour="sidebar-logout"]',
    title: '🔐 Logout',
    description: 'Safely logout of your session. Automations continue running.',
    why: 'Keeps your account secure on shared devices.',
    tip: null,
    placement: 'right',
    icon: '🔐',
  },
];

export default tourSteps;
