/**
 * UwoConnect Comprehensive Product Tour Configuration
 * ----------------------------------------------------
 * Covers all features across the Dashboard and Sidebar navigation menu.
 */

const tourSteps = [
  {
    id: 'welcome',
    page: '/client',
    selector: '[data-tour="dashboard-welcome"]',
    title: '👋 Welcome to UwoConnect!',
    description: 'This is your AI & Omnichannel Automation Command Center. Let us take you on a quick guided tour of all your powerful workspace tools.',
    why: 'Helps you set up, understand, and master all platform features in minutes.',
    tip: 'Press ESC anytime to pause, or use Next / Prev buttons below.',
    placement: 'bottom',
    icon: '🚀',
  },
  {
    id: 'sidebar-nav',
    page: null,
    selector: '[data-tour="sidebar-nav"]',
    title: '🗂️ Unified Sidebar Menu',
    description: 'Access all your business automation modules, inbox, CRM, and channel settings from this navigation panel.',
    why: 'One-click access to all customer touchpoints and AI engines.',
    tip: 'The active menu section is highlighted with a green indicator bar.',
    placement: 'right',
    icon: '🗂️',
  },
  {
    id: 'dashboard-stats',
    page: '/client',
    selector: '[data-tour="dashboard-stats"]',
    title: '📊 Real-Time Analytics',
    description: 'Monitor total active conversations, AI response rates, workflow executions, and system health status live.',
    why: 'Gives an instant high-level overview of your customer engagement.',
    tip: null,
    placement: 'bottom',
    icon: '📊',
  },
  {
    id: 'dashboard-launch-btn',
    page: '/client',
    selector: '[data-tour="dashboard-launch-btn"]',
    title: '⚡ Visual Flow Creator',
    description: 'Click here to instantly launch the drag-and-drop workflow builder.',
    why: 'Quickly design lead collection funnels and chat automations.',
    tip: null,
    placement: 'bottom',
    icon: '⚡',
  },
  {
    id: 'sidebar-channels',
    page: null,
    selector: '[data-tour="sidebar-channels"]',
    title: '🔗 Channel Connections',
    description: 'Connect your WhatsApp Cloud API, Instagram Direct, Facebook Messenger, and Telegram accounts.',
    why: 'Required to route incoming customer messages to AI bots and human agents.',
    tip: 'WhatsApp API is recommended for official business marketing.',
    placement: 'right',
    icon: '🔗',
  },
  {
    id: 'sidebar-youtube',
    page: null,
    selector: '[data-tour="sidebar-youtube"]',
    title: '🎬 YouTube Automation & AI Bot',
    description: 'Manage YouTube channel videos, auto-reply to comments via RAG AI or custom keyword rules, and trigger WhatsApp broadcast alerts on new video uploads.',
    why: 'Automates video community moderation and converts viewers into leads.',
    tip: 'Define Custom Keyword Rules for instant pricing & FAQ replies.',
    placement: 'right',
    icon: '🎬',
  },
  {
    id: 'sidebar-google-news',
    page: null,
    selector: '[data-tour="sidebar-google-news"]',
    title: '📰 Google News & Content Hub',
    description: 'Generate AI news articles, blog posts, and manage search indexable press content automatically.',
    why: 'Boosts organic web presence and brand search authority.',
    tip: null,
    placement: 'right',
    icon: '📰',
  },
  {
    id: 'sidebar-automations',
    page: null,
    selector: '[data-tour="sidebar-automations"]',
    title: '⚡ Instant Auto Replies',
    description: 'Configure instant keyword triggers for common questions like business hours, pricing, and location.',
    why: 'Guarantees 24/7 instant responses to incoming customer queries.',
    tip: null,
    placement: 'right',
    icon: '⚡',
  },
  {
    id: 'sidebar-workflows',
    page: null,
    selector: '[data-tour="sidebar-workflows"]',
    title: '🔀 Visual Workflows Builder',
    description: 'Build multi-step interactive chatbots with condition branches, delays, tags, and webhook actions.',
    why: 'Handles complex lead qualification, booking funnels, and automated follow-ups.',
    tip: null,
    placement: 'right',
    icon: '🔀',
  },
  {
    id: 'sidebar-crm',
    page: null,
    selector: '[data-tour="sidebar-crm"]',
    title: '👥 Leads & Smart CRM',
    description: 'View all captured contacts, full conversation histories, lead statuses, and custom profile tags.',
    why: 'Centralized customer database to track and convert leads into sales.',
    tip: null,
    placement: 'right',
    icon: '👥',
  },
  {
    id: 'sidebar-inbox',
    page: null,
    selector: '[data-tour="sidebar-inbox"]',
    title: '💬 Unified Team Inbox',
    description: 'A single chat dashboard for human agents to take over conversations from AI and chat live across channels.',
    why: 'Ensures seamless handoff between AI automation and human support agents.',
    tip: null,
    placement: 'right',
    icon: '💬',
  },
  {
    id: 'sidebar-campaigns',
    page: null,
    selector: '[data-tour="sidebar-campaigns"]',
    title: '📢 Broadcasts & Marketing',
    description: 'Send bulk WhatsApp marketing templates, promotional offers, or announcement broadcasts to contact lists.',
    why: 'Drives customer re-engagement and sales conversions.',
    tip: null,
    placement: 'right',
    icon: '📢',
  },
  {
    id: 'sidebar-knowledge',
    page: null,
    selector: '[data-tour="sidebar-knowledge"]',
    title: '🧠 AI Knowledge Base (RAG)',
    description: 'Upload PDF documents, company guidelines, FAQs, or web links to train your custom AI Assistant.',
    why: 'Enables AI to provide accurate, business-specific answers.',
    tip: null,
    placement: 'right',
    icon: '🧠',
  },
  {
    id: 'sidebar-catalog',
    page: null,
    selector: '[data-tour="sidebar-catalog"]',
    title: '🛍️ E-Commerce Catalog',
    description: 'Create and manage product catalogs, prices, descriptions, and shareable checkout cards.',
    why: 'Showcase products directly inside customer chat windows.',
    tip: null,
    placement: 'right',
    icon: '🛍️',
  },
  {
    id: 'sidebar-orders',
    page: null,
    selector: '[data-tour="sidebar-orders"]',
    title: '🧾 Orders & Receipts',
    description: 'Track customer orders, payment status, invoice receipts, and fulfillment status in real-time.',
    why: 'Keeps e-commerce sales and payment tracking organized.',
    tip: null,
    placement: 'right',
    icon: '🧾',
  },
  {
    id: 'sidebar-team',
    page: null,
    selector: '[data-tour="sidebar-team"]',
    title: '🛡️ Team & Role Management',
    description: 'Invite workspace team members, assign agent roles, and set custom feature permissions.',
    why: 'Scale support operations while keeping account controls secure.',
    tip: null,
    placement: 'right',
    icon: '🛡️',
  },
  {
    id: 'sidebar-reports',
    page: null,
    selector: '[data-tour="sidebar-reports"]',
    title: '📋 Work & Productivity Reports',
    description: 'Generate detailed analytics reports on team performance, chat response times, and workflow execution logs.',
    why: 'Helps evaluate agent productivity and automation efficiency.',
    tip: null,
    placement: 'right',
    icon: '📋',
  },
  {
    id: 'sidebar-settings',
    page: null,
    selector: '[data-tour="sidebar-settings"]',
    title: '⚙️ Workspace Settings',
    description: 'Configure business details, API credentials, Webhook integrations, AI model defaults, and billing.',
    why: 'Central management for workspace preferences and keys.',
    tip: null,
    placement: 'right',
    icon: '⚙️',
  },
  {
    id: 'sidebar-support',
    page: null,
    selector: '[data-tour="sidebar-support"]',
    title: '🎧 Help & Support Desk',
    description: 'Submit support tickets, access platform user guides, or directly contact technical support.',
    why: 'Get immediate help whenever you need assistance.',
    tip: null,
    placement: 'right',
    icon: '🎧',
  },
  {
    id: 'header-team-chat',
    page: null,
    selector: '[data-tour="header-team-chat"]',
    title: '💬 Live Team Workspace Room',
    description: 'Open internal team chat sidebar to communicate with online agents and supervisors in real-time.',
    why: 'Fosters internal collaboration without leaving the dashboard.',
    tip: null,
    placement: 'bottom',
    icon: '💬',
  },
  {
    id: 'sidebar-logout',
    page: null,
    selector: '[data-tour="sidebar-logout"]',
    title: '🔐 Secure Logout',
    description: 'Safely log out of your session. All automated bots and workflows continue running in the background 24/7.',
    why: 'Protects account access on shared devices while keeping background operations active.',
    tip: null,
    placement: 'right',
    icon: '🔐',
  },
];

export default tourSteps;
